{{ if eq .category "work" -}}
"bin/smproxy.sh":
  type: "file"
  url: "https://code.corp.surveymonkey.com/raw/ACMe/ssh_proxy/master/smproxy.sh"
  executable: true
".ssh/config.d/sm-proxy":
  type: "file"
  url: "https://code.corp.surveymonkey.com/raw/ACMe/ssh_proxy/master/config"
{{- end }}
{{ if eq .chezmoi.os "darwin" -}}
".iterm2_shell_integration.zsh":
  type: "file"
  url: "https://iterm2.com/shell_integration/zsh"
".iterm2":
  type: archive
  url: "https://github.com/gnachman/iTerm2-shell-integration/archive/main.tar.gz"
  stripComponents: 2
  exact: true
  refreshPeriod: "168h"
  include:
    - "*"
    - "*/utilities"
    - "*/utilities/**"
{{- end }}
".vim/bundle/Vundle.vim":
  type: "git-repo"
  url: "https://github.com/VundleVim/Vundle.vim.git"
  refreshPeriod: "168h"
{{- $helm_plugin_dir := output "helm" "env" "HELM_PLUGINS" | trim | trimPrefix .chezmoi.homeDir | trimPrefix "/" }}
{{ joinPath $helm_plugin_dir "helm-unittest.git" | quote }}:
  type: "git-repo"
  url: "https://github.com/helm-unittest/helm-unittest.git"
  refreshPeriod: "168h"
