#!/bin/zsh

file=${ZDOTDIR-$HOME}/${(%):-%1N}.d

if [ -d $file ]; then
    for i in $file/*(N); do
        case $i in *~) continue;; esac
        source $i
    done
fi

if [ -f /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi
