#!/bin/zsh

if [ -f /opt/homebrew/bin/brew ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

file=${ZDOTDIR-$HOME}/${(%):-%1N}.d

if [ -d $file ]; then
    for i in $file/*(N); do
        case $i in *~) continue;; esac
        source $i
    done
fi

autoload -Uz bashcompinit; bashcompinit
autoload -Uz compinit
if [[ -n ~/.zcompdump(#qNmh-24) ]]; then
  compinit -C
else
  compinit
fi
