[tools]
act = "0.2.88"
actionlint = "1.7.12"
atuin = "18.16.0"
container-structure-test = "1.22.1"
direnv = "2.37.1"
go = "1.26.2"
golangci-lint = "2.12.1"
hadolint = "2.14.0"
helm = "4.1.4"
helm-docs = "1.14.2"
helmfile = "1.4.5"
k9s = "0.50.18"
kustomize = "5.8.1"
node = { version = "25.9.0", os = ["macos"] }
poetry = "2.3.4"
python = "3.14.4"
rust = "1.95.0"
skaffold = "2.19.0"
talhelper = "3.1.9"
talosctl = "1.13.0"
terraform = "1.15.1"
terraform-docs = "0.22.0"
terraformer = "0.8.30"
tflint = "0.62.0"
tfmigrate = "0.4.4"
tfsec = "1.28.14"
trivy = "0.70.0"
uv = "0.11.8"
yq = "4.53.2"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "terraform"]
