[tools]
actionlint = "1.7.12"
atuin = "18.17.1"
container-structure-test = "1.22.1"
fzf = "0.74.1"
go = "1.26.5"
golangci-lint = "2.12.2"
hadolint = "2.14.0"
helm = "4.2.3"
helm-docs = "1.14.2"
helmfile = "1.7.1"
k9s = "0.51.0"
kustomize = "5.8.1"
node = { version = "25.9.0", os = ["macos"] }
poetry = "2.4.1"
python = "3.14.6"
talhelper = "3.1.13"
talosctl = "1.13.7"
terraform = "1.15.8"
terraform-docs = "0.24.0"
tflint = "0.64.0"
tfmigrate = "0.4.5"
trivy = "0.72.0"
uv = "0.11.31"
yq = "4.53.3"
zoxide = "0.10.0"

[settings]
env_file=".envrc"
ruby.compile = false
idiomatic_version_file_enable_tools = ["ruby", "terraform"]
