#!/usr/bin/env bash
if [ ! -z "${OPENSC_PKCS11}" ] && [ -f "${OPENSC_PKCS11}" ]; then
    function yubiadd() {
        ssh-add -s "$OPENSC_PKCS11"
    }
    function yubidel() {
        ssh-add -e "$OPENSC_PKCS11"
    }
    function yubireset() {
        yubidel
        yubiadd
    }
fi
