tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/completions'
tap 'homebrew/core'
brew 'dockutil'
brew 'git'
brew 'mas'
brew 'shellcheck'
brew 'stow'
brew 'homebrew/completions/brew-cask-completion'
cask 'evernote'
cask 'google-chrome'
cask 'google-drive'
cask 'iterm2'
cask 'keepassx'
cask 'macdown'
cask 'slack'
mas 'Pocket', id: 568494494
