#!/usr/bin/env bash

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  # Are Xcode CLI tools installed?
  xcode-select -p &> /dev/null || {
    echo "==> Installing Xcode CLI tools…"
    xcode-select --install
    sudo xcodebuild -license
  }

  # Is homebrew installed?
  command -v brew &> /dev/null || {
    echo "==> Installing homebrew…"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  }

  brew update

  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
elif [ "$(uname -o)" = "Android" ]; then
  # Is stow installed?
  command -v stow &> /dev/null || {
    echo "==> Installing stow..."
    pkg install stow
  }
elif [ "$(uname -s)" = "Linux" ]; then
  # Is stow installed?
  command -v stow &> /dev/null || {
    echo "==> Installing stow..."
    echo "** Won't guess at how to install stow- install it manually **"
    exit 1
  }
fi
