#!/usr/bin/env bash

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ -d work ]; then
  stow -R work
fi

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  # Are Xcode CLI tools installed?
  xcode-select -p &> /dev/null || {
    echo "==> Installing Xcode CLI tools…"
    xcode-select --install
    sudo xcodebuild -license
  }

  # Is homebrew installed?
  which brew &> /dev/null || {
    echo "==> Installing homebrew…"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  }

  brew update

  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies…"
    brew bundle
  }
fi
