#!/usr/bin/env bash

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

cd "$(dirname "$0")/.." || exit

script/bootstrap

stow -R bash direnv docker git gnupg kubernetes pwdhash python ruby screen travisci vim zsh

if [ "$(uname -s)" = "Darwin" ]; then
    script/setup."$(uname -s)"
elif [ "$(uname -o)" = "Android" ]; then
    script/setup."$(uname -o)"
elif [ "$(uname -s)" = "Linux" ]; then
    script/setup."$(uname -s)"
fi

if [ ! -d ~/.vim/bundle/Vundle.vim ]; then
    echo "==> Installing vim bundles…"
    mkdir -p ~/.vim/bundle
    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
    vim +PluginInstall +qall
fi

[ -x script/setup.work."$(uname -s)" ] && script/setup.work."$(uname -s)"

echo "==> Ready to go!"
