#!/usr/bin/env bash

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

stow -R bash ctags direnv git homebrew puppet python ruby screen travisci vagrant vim

if [ "$(uname -s)" = "Darwin" ]; then
    stow -R osx

    if [ -f "${HOME}/.Brewfile" ]; then
        brew update
        brew bundle check --global >/dev/null 2>&1  || {
            echo "==> Installing Global Homebrew dependencies…"
            brew bundle --global
        }
    fi

    for src_completion in /Applications/Docker.app/Contents/Resources/etc/*.bash-completion ; do
        dest_completion="/usr/local/etc/bash_completion.d/$(basename "$src_completion")"
        if [[ ! ( -L "$dest_completion" || -e "$dest_completion" ) ]]; then
            ln -s "$src_completion" "$dest_completion"
        fi
    done
fi

if [ ! -d ~/.vim/bundle/Vundle.vim ]; then
    mkdir -p ~/.vim/bundle
    git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
    vim +PluginInstall +qall
fi

echo "==> Ready to go!"
