#!/bin/sh

# script/update: Update application to run for its current checkout.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "==> Modified files in this repo..."
git status

echo "==> Brew status..."
brew bundle check --global

echo "==> Stuff not in global brewfile..."
rm /tmp/Brewfile*
brew bundle dump --file=/tmp/Brewfile
sort /tmp/Brewfile > /tmp/Brewfile.srt
sort homebrew/.Brewfile > /tmp/Brewfile.srt.orig
diff /tmp/Brewfile.srt /tmp/Brewfile.srt.orig
