#!/usr/bin/env bash

# script/update: Update application to run for its current checkout.

set -e

cd "$(dirname "$0")/.."

script/bootstrap

echo "==> Modified files in this repo..."
git status

echo "==> Brew status..."
brew bundle check --global --no-upgrade --verbose || true

rm -f /tmp/Brewfile*
brew bundle dump --file=/dev/stdout | sort > /tmp/Brewfile.current
sort ~/.Brewfile > /tmp/Brewfile.global
echo "==> Stuff installed but not in global brewfile..."
comm -23 /tmp/Brewfile.current /tmp/Brewfile.global
echo "==> Stuff in global brewfile but not installed..."
comm -13 /tmp/Brewfile.current /tmp/Brewfile.global
