# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# --- Global ---
add_newline = true
command_timeout = 1000

format = """$fill$all$directory$character"""
#right_format = """$directory$time"""

[aws]
format = 'on [$symbol($profile)(\[$duration\])]($style)'

[directory]
fish_style_pwd_dir_length = 1

[fill]
symbol = ' '

[gcloud]
disabled = true

[git_metrics]
disabled = false

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) '

[status]
disabled = false

[terraform]
symbol = "󱁢"
format = 'via [$symbol$version $workspace]($style) '
version_format = '${raw}'

[time]
disabled = false
format = '[$time]($style) '
style = "dimmed white"
